spring:
  profiles:
    active: develop
  thymeleaf:
    prefix: classpath:/static/

jenkins:
  ipv4: 127.0.0.1
  ipv6: 0:0:0:0:0:0:0:1 #localhost

---

spring:
  profiles: develop
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


logging:
  config: "classpath:logback-dev.xml"
