spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  config: "classpath:logback-dev.xml"

---
spring:
  profiles: production

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.74.141:3306/woowacrew?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: woowacrew

  jpa:
    hibernate:
      ddl-auto: create
    database-platform:  org.hibernate.dialect.MySQL8Dialect

logging:
  config: "classpath:logback-prod.xml"
