name: Build Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: copy secret
        env:
          github_secret: ${{ secrets.githubClientAuthorization }}
          slack_secret: ${{ secrets.slackInfo }}
          slack_test_secret: ${{ secrets.slackTestInfo }}
        run: echo "$github_secret" > ./src/main/resources/github.yml | echo "$slack_secret" > ./src/main/resources/slack.yml | echo "$slack_test_secret" > ./src/test/resources/slack.yml
      - name: Build with Gradle
        run: ./gradlew build
