name: Dockerhub Push

on:
  push:
    branches:
      - develop
      - actions-test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test -x acceptanceTest -x asciidoctor
      - name: Docker build
        run: |
          docker build . -t oeeen/woowacrew:lts
      - name: Dockerhub push
        run: |
          docker login -u ${{secrets.DOCKER_USER_NAME}} --password ${{secrets.DOCKER_USER_PASSWORD}}
          docker push oeeen/woowacrew:lts