name: Dockerhub Push

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: execute build
        run: |
          docker build . -t oeeen/woowacrew:lts
      - name: docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER_NAME}} --password ${{secrets.DOCKER_USER_PASSWORD}}
          docker push oeeen/woowacrew:lts