name: Dockerhub Push

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: copy secret
        env:
          application_config_dev: ${{ secrets.APPLICATION_CONFIG_DEV }}
          application_config_prod: ${{ secrets.APPLICATION_CONFIG_PROD }}
          application_config_test: ${{ secrets.APPLICATION_CONFIG_TEST }}
        run: echo "$application_config_prod" > ./woowacrew-web/src/main/resources/application-prod.yml | echo "$application_config_dev" > ./woowacrew-web/src/main/resources/application-dev.yml | echo "$application_config_test" > ./woowacrew-web/src/main/resources/application-test.yml
      - name: Build with Gradle
        run: ./gradlew woowacrew-web:clean woowacrew-web:build
      - name: Docker build
        run: |
          docker build -t oeeen/woowacrew:latest .
      - name: Dockerhub push
        run: |
          docker login -u ${{secrets.DOCKER_USER_NAME}} --password ${{secrets.DOCKER_USER_PASSWORD}}
          docker push oeeen/woowacrew:latest